<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="38489" started-at="2018-11-07T00:44:49Z" finished-at="2018-11-07T00:45:27Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="38489" started-at="2018-11-07T00:44:49Z" finished-at="2018-11-07T00:45:27Z">
      <class name="com.test.Test1Test">
        <test-method status="PASS" signature="SetUpMethod()[pri:0, instance:com.test.Test1Test@1877ab81]" name="SetUpMethod" is-config="true" duration-ms="4812" started-at="2018-11-07T00:44:49Z" finished-at="2018-11-07T00:44:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUpMethod -->
        <test-method status="FAIL" signature="test_Page_Title()[pri:0, instance:com.test.Test1Test@1877ab81]" name="test_Page_Title" duration-ms="3555" started-at="2018-11-07T00:44:53Z" finished-at="2018-11-07T00:44:57Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.test.Test1Test.test_Page_Title(Test1Test.java:59)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_Page_Title -->
        <test-method status="PASS" signature="Close()[pri:0, instance:com.test.Test1Test@1877ab81]" name="Close" is-config="true" duration-ms="0" started-at="2018-11-07T00:44:57Z" finished-at="2018-11-07T00:44:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Close -->
        <test-method status="PASS" signature="SetUpMethod()[pri:0, instance:com.test.Test1Test@1877ab81]" name="SetUpMethod" is-config="true" duration-ms="6374" started-at="2018-11-07T00:44:57Z" finished-at="2018-11-07T00:45:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUpMethod -->
        <test-method status="PASS" signature="test_Login_InvalidCredentials()[pri:1, instance:com.test.Test1Test@1877ab81]" name="test_Login_InvalidCredentials" duration-ms="10483" started-at="2018-11-07T00:45:03Z" finished-at="2018-11-07T00:45:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_Login_InvalidCredentials -->
        <test-method status="PASS" signature="Close()[pri:0, instance:com.test.Test1Test@1877ab81]" name="Close" is-config="true" duration-ms="0" started-at="2018-11-07T00:45:14Z" finished-at="2018-11-07T00:45:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Close -->
        <test-method status="PASS" signature="SetUpMethod()[pri:0, instance:com.test.Test1Test@1877ab81]" name="SetUpMethod" is-config="true" duration-ms="6431" started-at="2018-11-07T00:45:14Z" finished-at="2018-11-07T00:45:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUpMethod -->
        <test-method status="PASS" signature="test_FAQ_Page()[pri:2, instance:com.test.Test1Test@1877ab81]" name="test_FAQ_Page" duration-ms="6809" started-at="2018-11-07T00:45:20Z" finished-at="2018-11-07T00:45:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_FAQ_Page -->
        <test-method status="PASS" signature="Close()[pri:0, instance:com.test.Test1Test@1877ab81]" name="Close" is-config="true" duration-ms="0" started-at="2018-11-07T00:45:27Z" finished-at="2018-11-07T00:45:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Close -->
      </class> <!-- com.test.Test1Test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
